# Name: Ruturajsinh Udaysinh Vaghela
# Reg No: 24-27-07
# Programme: MTech Data Science
# Assignment Number: 2

# Q1

In [1]:
# a)

import numpy as np
var1 = np.arange(0, 31)
print(var1)
var1.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


(31,)

In [2]:
# b)
# Since var1 has 31 elements and 31 can't be converted into 2D. So removing the first element to make it 30

var1 = np.delete(var1, 0)

var2 = var1.reshape(5, 6)
print(var2)
var2.shape

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


(5, 6)

In [3]:
# c)

var3 = var1.reshape(2, 5, 3)
print(var3)
var3.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]


(2, 5, 3)

In [4]:
# d)

var2[1][0] = -1
print(f"Var 2: \n{var2} \n\n Var 1: \n{var1} \n\n Var 3: \n{var3}")

print('''
Since we used reshape on var1 to get var2 and var3 it creates a copy or the numpy array
Hence if the elements of 1 array is modified... The other 2 arrays elements will also be modified
Therefor when we changed var2 elements as -1 it also reflected in var1 and var3
''')

Var 2: 
[[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 

 Var 1: 
[ 1  2  3  4  5  6 -1  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 

 Var 3: 
[[[ 1  2  3]
  [ 4  5  6]
  [-1  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]

Since we used reshape on var1 to get var2 and var3 it creates a copy or the numpy array
Hence if the elements of 1 array is modified... The other 2 arrays elements will also be modified
Therefor when we changed var2 elements as -1 it also reflected in var1 and var3



In [6]:
# e)

# i)
res1 = np.sum(var3, axis = 1)
print("Sum over 2nd Dimension: \n", res1)

# ii)
res2 = np.sum(var3, axis = 2)
print("\nSum over 3rd Dimension: \n", res2)

# iii)
res3 = np.sum(var3, axis = (0, 2))
print("\nSum over 1st and 3rd Dimensions: \n", res3)

Sum over 2nd Dimension: 
 [[ 27  40  45]
 [110 115 120]]

Sum over 3rd Dimension: 
 [[ 6 15 16 33 42]
 [51 60 69 78 87]]

Sum over 1st and 3rd Dimensions: 
 [ 57  75  85 111 129]


In [10]:
# f)

print("Var2: \n", var2)
# i)
res1 = var2[1]
print("\n2nd Row of var2: \n", res1)

# ii)
res2 = var2[:, -1]
print("\nLast column of var2: \n", res2)

# iii)
res3 = var2[:2, -2:]
print("\nTop Right 2×2 Submatrix of var2: \n", res3)

Var2: 
 [[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

2nd Row of var2: 
 [-1  8  9 10 11 12]

Last column of var2: 
 [ 6 12 18 24 30]

Top Right 2×2 Submatrix of var2: 
 [[ 5  6]
 [11 12]]


# Q2

In [12]:
# a)

vector = np.arange(10) + 1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# b)

A = vector.reshape(10, 1) + vector
print(A)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [17]:
# c)

import numpy.random as npr
data = np.exp(npr.randn(50, 5))

In [18]:
# d)

print(data)

[[ 1.03540376  0.32884487  0.2041805   0.16389041  3.17432344]
 [ 0.65233132  0.17048763  3.68866082  0.18364127  2.39669719]
 [ 1.9434254   1.88433181  0.62566655  0.30496564  0.37400965]
 [ 0.31637298  0.29774947  1.13593444  1.3723215   7.30320315]
 [ 0.15974331  0.44263702  1.4181086   0.1656185   0.36385167]
 [ 1.59628369  3.51131038  1.33953283  0.77714533  0.88223619]
 [ 2.04747583  0.44492639  0.30468473  0.68722602  0.88669336]
 [ 3.47633574  0.92106767  0.64819553  0.20584494  0.33625396]
 [ 2.12048548  1.43327094  0.61994934  1.24343938  0.40237315]
 [ 0.32395723  4.11808269  1.81554419  0.42540764  6.01456447]
 [ 2.06500103  2.42584004  2.78394267  0.27204254  0.93305398]
 [ 2.43545405  2.54995427  0.43742659  0.71210955  1.54000187]
 [ 3.45851146  0.68550593  2.57525154  1.32884076  6.11538769]
 [ 1.39116844  2.33679793  0.59740371  2.19370203  1.00664067]
 [ 0.34809204  0.55288192  0.65633958  1.67873178  0.77780403]
 [ 0.16653839  0.06216871  2.90310372  0.80917034  2.31

In [22]:
# e)

mean = np.mean(data, axis = 0)
s_dev = np.std(data, axis = 0)

print(f"Mean: {mean}\nStandard Deviation: {s_dev}")

Mean: [1.67336042 1.93149208 1.35281444 1.44438315 1.93898773]
Standard Deviation: [1.59193028 2.47871806 1.54137272 2.03958503 1.64499246]


In [23]:
# f)

norm = (data - mean)/s_dev

mean = np.mean(norm, axis = 0)
s_dev = np.std(norm, axis = 0)

print(f"Mean: {mean}\nStandard Deviation: {s_dev}")

Mean: [-1.75415238e-16 -1.93178806e-16 -5.21804822e-17 -1.64313008e-16
 -2.73114864e-16]
Standard Deviation: [1. 1. 1. 1. 1.]


# Q3

In [54]:
# a)

def vandermonde(N):
    vec = np.arange(N) + 1
    return vec[:, np.newaxis] ** (vec - 1)
    
res = vandermonde(12)
print(res)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [55]:
# b)

x = np.ones(12)
b = np.dot(res, x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [61]:
# c)

from numpy.linalg import inv
x2 = inv(res).dot(b)
print(x2)

[1.00537872 0.99484253 0.99961472 1.00018311 0.99998856 1.00000012
 1.         1.         1.         1.         1.         1.        ]


In [66]:
# d)

x3 = np.linalg.solve(res, b)
print(x3)

[0.99999915 1.00000115 0.99999995 0.99999962 1.00000017 0.99999997
 1.         1.         1.         1.         1.         1.        ]


# https://github.com/Ruturaj18/Ruturaj_Vaghela_24-27-07.git